language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "10.6"
before_script:
  - psql -c "CREATE DATABASE politico_test_db;" -U postgres
  - psql -c "CREATE USER tev WITH PASSWORD '8279';" -U postgres
env:
  - SECRET_KEY="ABIGSECRET" DATABASE_TEST_URL="postgres://tev:8279@localhost/politico_test_db"
script:
  - python -m pytest --cov=app/api
after_success:
  - coveralls
