language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432 SECRET_KEY="ABIGSECRET"
before_script:
  - psql -c 'create database politico_test_db;' -U postgres

script:
  - python -m pytest --cov=app/api
after_success:
  - coveralls
