language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - psql -c "CREATE DATABASE politico_db;" -U postgres
  - psql -c "CREATE USER tev WITH PASSWORD '8279';" -U postgres
env:
  - DATABASE_URL="postgres://tev:8279@localhost/politico_db"
  - DATABASE_TEST_URL="postgres://tev:8279@localhost/test_db"
script:
  - python -m pytest --cov=app/api
after_success:
  - coveralls
